local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
digital_ocean:
  service: S3
  access_key_id: <%= ENV.fetch("DO_ACCESS_KEY") %>
  secret_access_key: <%= ENV.fetch("DO_SECRET") %>
  region: nyc3
  bucket: ep-files
  endpoint: "https://nyc3.digitaloceanspaces.com"
